global:
  scrape_interval:

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - "node_exporter:9100"

remote_write:
  - url: 'http://192.168.122.68:3000'
    name: 'grafana'
